### PR TITLE
app visibility detector

### PR DESCRIPTION
**Pull request by peterBrxwn**

### CODE REVIEW

**Comment by peterBrxwn** [comment]
[[Flutter] if the app is visible or not, detect this.  When event or view is recorded, add segmentation {visible: 1 or 0}](https://trello.com/c/4771HIOT/1945-flutter-if-the-app-is-visible-or-not-detect-this-when-event-or-view-is-recorded-add-segmentation-visible-1-or-0)

**Review by turtledreams — CHANGES_REQUESTED** [review]
lets add a config option for enabling visibility tracking:
enableVisibilityTracking()

Also please test what happens if you init the SDK while the app was in background.
Reason: we do a similar tracking for app visibility in android and some issues were found depending on the initial visibility we assume and the real state of the app.
we need to know a lot of possibilities

**Comment by peterBrxwn** [comment]
Done

**Review by turtledreams — CHANGES_REQUESTED** [review]
needs tests to be added

**Review by arifBurakDemiray — COMMENTED** [review]
Helooo 🙌 
Please test and write the results here.

It looks cool and it would be great to have.

**Comment by peterBrxwn** [comment]
Added tests for visibility

**Pull request closed without merging**
